name: gestion_equipe_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_messaging_web: ^3.10.5
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0 
  google_fonts: ^6.2.1
  jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  logger: ^2.5.0
  fl_chart: ^0.70.2
  socket_io_client: ^3.1.1
  fluttertoast: ^8.0.8
  intl: ^0.19.0  # Modifier cette ligne
  provider: ^6.0.0
  pdf: ^3.10.0
  printing: ^5.10.0
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/   # Inclut tous les fichiers dans ce dossier
  uses-material-design: true
  generate: true   # Ajouter cette ligne pour activer la génération automatique de localisations
