name: gestion_equipe_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.2.0  # ✅ Garder une seule fois
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  azure_ad_authentication: ^1.0.5
  logger: ^2.5.0
  fl_chart: ^0.36.0  # Utiliser la dernière version disponible
  socket_io_client: ^3.0.2
  intl: ^0.19.0  # Mettre à jour ici pour être compatible avec flutter_localizations
  provider: ^6.0.0
  flutter_localizations:
    sdk: flutter  # Ajouter pour gérer les localisations


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/   # Inclut tous les fichiers dans ce dossier
  uses-material-design: true
  generate: true   # Ajouter cette ligne pour activer la génération automatique de localisations
